// 개발(C)의 계약은 G와 독립적으로 유지한다. 공통 인증·AI 계약은 재사용한다.
export * from './index';
export {
  DEVELOP_REQUEST_MODES,
  type DevelopRequestModeType,
  DevelopRequestMode,
  DEVELOP_REQUEST_MODE_LABELS,
  DEVELOP_BUDGET_RANGES,
  type DevelopBudgetRangeType,
  DevelopBudgetRange,
  DEVELOP_BUDGET_RANGE_LABELS,
  DEVELOP_CURRENT_STAGES,
  type DevelopCurrentStageType,
  DevelopCurrentStage,
  DEVELOP_CURRENT_STAGE_LABELS,
  DEVELOP_TARGET_STAGES,
  type DevelopTargetStageType,
  DevelopTargetStage,
  DEVELOP_TARGET_STAGE_LABELS,
  DEVELOP_PROTOTYPE_MODES,
  type DevelopPrototypeModeType,
  DevelopPrototypeMode,
  DEVELOP_PROTOTYPE_MODE_LABELS,
  DEVELOP_PRODUCTION_SCOPES,
  type DevelopProductionScopeType,
  DevelopProductionScope,
  DEVELOP_PRODUCTION_SCOPE_LABELS,
  DEVELOP_PRIORITIES,
  type DevelopPriorityType,
  DevelopPriority,
  DEVELOP_PRIORITY_LABELS,
  DEVELOP_SOURCING_MODES,
  type DevelopSourcingModeType,
  DevelopSourcingMode,
  DEVELOP_SOURCING_MODE_LABELS,
  DEVELOP_DELIVERY_FORMS,
  type DevelopDeliveryFormType,
  DevelopDeliveryForm,
  DEVELOP_DELIVERY_FORM_LABELS,
  DevelopProductionPlan,
  type DevelopProductionPlanType,
  EMPTY_DEVELOP_PRODUCTION,
  normalizeDevelopProduction,
  developProductionSummary,
  DEVELOP_DATE_RE,
  DevelopWishDate,
  developWishCode,
  developWishLabel,
  resolveDevelopServiceAreas,
  DEVELOP_REQUEST_STATUSES,
  type DevelopRequestStatusType,
  DevelopRequestStatus,
  DEVELOP_REQUEST_STATUS_LABELS,
  DEVELOP_PROGRESS_STEPS,
  isDevelopClosed,
  isDevelopEditable,
  isDevelopCustomerCancellable,
  DEVELOP_QUOTE_KINDS,
  type DevelopQuoteKindType,
  DevelopQuoteKind,
  DEVELOP_QUOTE_KIND_LABELS,
  DEVELOP_QUOTE_STATUSES,
  type DevelopQuoteStatusType,
  DevelopQuoteStatus,
  DEVELOP_QUOTE_STATUS_LABELS,
  DEVELOP_VAT_MODES,
  type DevelopVatModeType,
  DevelopVatMode,
  DEVELOP_VAT_MODE_LABELS,
  DEVELOP_VAT_RATE_BP,
  DEVELOP_MILESTONE_TRIGGERS,
  type DevelopMilestoneTriggerType,
  DevelopMilestoneTrigger,
  DEVELOP_MILESTONE_TRIGGER_LABELS,
  DEVELOP_MILESTONE_STATUSES,
  type DevelopMilestoneStatusType,
  DevelopMilestoneStatus,
  DEVELOP_MILESTONE_STATUS_LABELS,
  DEVELOP_EVENT_TYPES,
  type DevelopEventTypeType,
  DevelopEventType,
  DEVELOP_EVENT_TYPE_LABELS,
  DEVELOP_ADMIN_EVENT_TYPES,
  DevelopAdminEventType,
  DEVELOP_DIAGRAM_SOURCES,
  DevelopDiagramSource,
  DevelopContact,
  type DevelopContactType,
  DevelopRequestCreatePayload,
  type DevelopRequestCreatePayloadType,
  DevelopRequestUpdateBody,
  type DevelopRequestUpdateBodyType,
  developMergedIssues,
  DevelopCancelBody,
  type DevelopCancelBodyType,
  DevelopFileMeta,
  type DevelopFileMetaType,
  DevelopQuoteItemView,
  type DevelopQuoteItemViewType,
  DevelopMilestoneView,
  type DevelopMilestoneViewType,
  DevelopQuoteView,
  type DevelopQuoteViewType,
  DevelopEventView,
  type DevelopEventViewType,
  DEVELOP_AI_REVIEW_STATES,
  type DevelopAiReviewStateType,
  DevelopAiReviewState,
  DevelopRequestListItem,
  type DevelopRequestListItemType,
  DevelopRequestListQuery,
  type DevelopRequestListQueryType,
  DevelopRequestListResponse,
  type DevelopRequestListResponseType,
  DevelopPublicDiagram,
  type DevelopPublicDiagramType,
  DevelopWizardFields,
  type DevelopWizardFieldsType,
  DevelopRequestDetail,
  type DevelopRequestDetailType,
  DevelopRequestDetailResponse,
  type DevelopRequestDetailResponseType,
  DevelopRequestCreateResponse,
  type DevelopRequestCreateResponseType,
  DevelopRequestStatusResponse,
  type DevelopRequestStatusResponseType,
  DevelopFilesResponse,
  type DevelopFilesResponseType,
  DevelopQuoteAcceptBody,
  type DevelopQuoteAcceptBodyType,
  DevelopQuoteDeclineBody,
  type DevelopQuoteDeclineBodyType,
  DevelopCommentBody,
  type DevelopCommentBodyType,
  DevelopReviewDecisionBody,
  type DevelopReviewDecisionBodyType,
  DevelopQuoteResponse,
  type DevelopQuoteResponseType,
  DevelopEventResponse,
  type DevelopEventResponseType,
  DevelopCheckoutResponse,
  type DevelopCheckoutResponseType,
  type DevelopQuoteLineParsed,
  type DevelopQuoteLinesResult,
  parseDevelopQuoteLines,
  type DevelopQuoteAmounts,
  computeDevelopQuoteAmounts,
  splitDevelopMilestoneAmounts,
  DEVELOP_ADMIN_TABS,
  type DevelopAdminTabType,
  DevelopAdminTab,
  DEVELOP_ADMIN_TAB_LABELS,
  DEVELOP_ADMIN_SIGNALS,
  type DevelopAdminSignalType,
  DevelopAdminSignal,
  DEVELOP_ADMIN_SIGNAL_LABELS,
  AdminDevelopRequestListQuery,
  type AdminDevelopRequestListQueryType,
  AdminDevelopRequestCounts,
  type AdminDevelopRequestCountsType,
  AdminDevelopAiSummary,
  type AdminDevelopAiSummaryType,
  AdminDevelopOps,
  type AdminDevelopOpsType,
  AdminDevelopRequestListItem,
  type AdminDevelopRequestListItemType,
  AdminDevelopSignals,
  type AdminDevelopSignalsType,
  AdminDevelopRequestListResponse,
  type AdminDevelopRequestListResponseType,
  AdminDevelopReviewState,
  type AdminDevelopReviewStateType,
  AdminDevelopDiagramState,
  type AdminDevelopDiagramStateType,
  AdminDevelopRequestDetail,
  type AdminDevelopRequestDetailType,
  AdminDevelopRequestDetailResponse,
  type AdminDevelopRequestDetailResponseType,
  AdminDevelopRequestPatchBody,
  type AdminDevelopRequestPatchBodyType,
  AdminDevelopStatusBody,
  type AdminDevelopStatusBodyType,
  AdminDevelopReviewPutBody,
  type AdminDevelopReviewPutBodyType,
  AdminDevelopAiRunResponse,
  type AdminDevelopAiRunResponseType,
  AdminDevelopEventPayload,
  type AdminDevelopEventPayloadType,
  DevelopQuoteItemInput,
  type DevelopQuoteItemInputType,
  DevelopMilestoneInput,
  type DevelopMilestoneInputType,
  AdminDevelopQuoteBody,
  type AdminDevelopQuoteBodyType,
  AdminDevelopQuoteResponse,
  type AdminDevelopQuoteResponseType,
  AdminDevelopMilestoneMarkPaidBody,
  type AdminDevelopMilestoneMarkPaidBodyType,
  DevelopOkResponse,
  type DevelopOkResponseType,
  DevelopMilestonePreset,
  AdminDevelopSettings,
  type AdminDevelopSettingsType,
  AdminDevelopSettingsResponse,
  type AdminDevelopSettingsResponseType,
  AdminDevelopSettingsUpdate,
  type AdminDevelopSettingsUpdateType,
  DEVELOP_DEFAULT_TERMS,
  DEVELOP_DEFAULT_EXCLUSIONS,
  DEVELOP_REVIEW_VERSION_KINDS,
  type DevelopReviewVersionKindType,
  DevelopReviewVersionKind,
  DEVELOP_REVIEW_VERSION_KIND_LABELS,
  DevelopReviewVersionMeta,
  type DevelopReviewVersionMetaType,
  AdminDevelopReviewVersionListResponse,
  type AdminDevelopReviewVersionListResponseType,
  AdminDevelopReviewVersionResponse,
  type AdminDevelopReviewVersionResponseType,
} from './schemas/develop-c';
import { apiRoutes as sharedRoutes } from './routes';
export const apiRoutes = {
  ...sharedRoutes,
  developRequests: '/api/develop-c/requests',
  developMyRequests: '/api/develop-c/my/requests',
  adminDevelopRequests: '/api/admin/develop-c/requests',
  adminDevelopQuotes: '/api/admin/develop-c/quotes',
  adminDevelopMilestones: '/api/admin/develop-c/milestones',
  adminDevelopFiles: '/api/admin/develop-c/files',
  adminDevelopSettings: '/api/admin/develop-c/settings',
  adminDevelopDocuments: '/api/admin/develop-c/documents',
} as const;
